// ── Currency utility ──────────────────────────────────────────
function fmt(amount) {
  const n = parseFloat(amount) || 0
  return `\u20a6 ${n.toLocaleString('en-NG', { minimumFractionDigits: 2 })}`
}

function fmtDate(str) {
  if (!str) return '—'
  return new Intl.DateTimeFormat('en-NG', {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
  }).format(new Date(str))
}

function fmtShort(str) {
  if (!str) return '—'
  return new Intl.DateTimeFormat('en-NG', {
    weekday: 'short', day: 'numeric', month: 'short',
  }).format(new Date(str))
}

const NAVY  = [15, 37, 87]
const CREAM = [250, 246, 240]
const GRAY  = [110, 110, 110]
const WHITE = [255, 255, 255]

function makeHeader(doc, { churchName, title, period, adminName }) {
  const w = doc.internal.pageSize.getWidth()

  // Navy banner
  doc.setFillColor(...NAVY)
  doc.rect(0, 0, w, 32, 'F')

  // Church name
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text(churchName || 'Sunday School', w / 2, 12, { align: 'center' })

  // Report title
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(200, 210, 240)
  doc.text(title, w / 2, 20, { align: 'center' })

  // Period
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text(period, w / 2, 27, { align: 'center' })

  // Generated by
  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...GRAY)
  const now = new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date())
  doc.text(`Generated ${now}${adminName ? `  ·  By ${adminName}` : ''}`, w / 2, 37, { align: 'center' })

  return 44 // next Y
}

function makeFooter(doc, { churchName, period }) {
  const pageCount = doc.internal.getNumberOfPages()
  const w = doc.internal.pageSize.getWidth()
  const h = doc.internal.pageSize.getHeight()

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setDrawColor(...NAVY)
    doc.setLineWidth(0.3)
    doc.line(14, h - 14, w - 14, h - 14)
    doc.setFontSize(7)
    doc.setTextColor(...GRAY)
    doc.text(`${churchName}  ·  ${period}`, 14, h - 8)
    doc.text(`Page ${i} of ${pageCount}`, w - 14, h - 8, { align: 'right' })
    doc.text('Sunday School Tracker', w / 2, h - 8, { align: 'center' })
  }
}

function summaryTable(doc, autoTable, y, stats) {
  autoTable(doc, {
    startY:     y,
    head:       [['Metric', 'Value']],
    body: [
      ['Total Present',           `${stats.present} (${stats.attendanceRate}%)`],
      ['Total Absent',            `${stats.absent}`],
      ['Total Offering Collected', fmt(stats.offering)],
      ['Classes Submitted',        `${stats.classCount}`],
    ],
    headStyles:         { fillColor: NAVY, textColor: WHITE, fontStyle: 'bold', fontSize: 8 },
    bodyStyles:         { fontSize: 8 },
    alternateRowStyles: { fillColor: CREAM },
    columnStyles:       { 0: { fontStyle: 'bold', cellWidth: 70 } },
    margin:             { left: 14, right: 14 },
  })
  return doc.lastAutoTable.finalY + 8
}

function groupTable(doc, autoTable, y, groups) {
  if (!groups?.length) return y

  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...NAVY)
  doc.text('Group Breakdown', 14, y)

  autoTable(doc, {
    startY: y + 4,
    head:   [['Group', 'Classes', 'Present', 'Absent', 'Rate', 'Offering']],
    body:   groups.map(g => [
      g.group,
      g.classes  ?? 0,
      g.present,
      g.absent  ?? (g.total - g.present),
      `${g.rate}%`,
      fmt(g.offering),
    ]),
    headStyles:         { fillColor: NAVY, textColor: WHITE, fontStyle: 'bold', fontSize: 8 },
    bodyStyles:         { fontSize: 8 },
    alternateRowStyles: { fillColor: CREAM },
    margin:             { left: 14, right: 14 },
  })
  return doc.lastAutoTable.finalY + 8
}

function classTable(doc, autoTable, y, classes) {
  if (!classes?.length) return y

  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...NAVY)
  doc.text('Class Details', 14, y)

  autoTable(doc, {
    startY: y + 4,
    head:   [['Class', 'Group', 'Present', 'Absent', 'On Time', 'Bible', 'Verse', 'Offering']],
    body:   classes.map(c => [
      c.className  || '—',
      c.groupName  || '—',
      c.presentCount ?? 0,
      c.absentCount  ?? 0,
      c.onTimeCount  ?? 0,
      c.bibleCount   ?? 0,
      c.verseCount   ?? 0,
      fmt(c.offering),
    ]),
    headStyles:         { fillColor: NAVY, textColor: WHITE, fontStyle: 'bold', fontSize: 7 },
    bodyStyles:         { fontSize: 7 },
    alternateRowStyles: { fillColor: CREAM },
    margin:             { left: 14, right: 14 },
  })
  return doc.lastAutoTable.finalY + 8
}

// ── Single Sunday PDF ─────────────────────────────────────────
export async function generateSundayPDF({ date, churchName, adminName, classes, groups }) {
  const { default: jsPDF }     = await import('jspdf')
  const { default: autoTable } = await import('jspdf-autotable')

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const period    = fmtDate(date)
  let y           = makeHeader(doc, {
    churchName,
    title:  'Sunday School Attendance Report',
    period,
    adminName,
  })

  // Summary
  const totalPresent  = (classes || []).reduce((s, c) => s + (c.presentCount || 0), 0)
  const totalRecords  = (classes || []).reduce((s, c) => s + (c.recordCount  || 0), 0)
  const totalOffering = (classes || []).reduce((s, c) => s + (c.offering     || 0), 0)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...NAVY)
  doc.text('Summary', 14, y)
  y += 4

  y = summaryTable(doc, autoTable, y, {
    present:        totalPresent,
    absent:         totalRecords - totalPresent,
    attendanceRate: totalRecords > 0 ? Math.round((totalPresent / totalRecords) * 100) : 0,
    offering:       totalOffering,
    classCount:     (classes || []).length,
  })

  y = groupTable(doc, autoTable, y, groups)
  y = classTable(doc, autoTable, y, classes)

  makeFooter(doc, { churchName, period })
  doc.save(`Attendance-${date}.pdf`)
}

// ── Monthly PDF (one section per Sunday, summary at end) ──────
export async function generateMonthPDF({ month, year, churchName, adminName, sundays, groups }) {
  const { default: jsPDF }     = await import('jspdf')
  const { default: autoTable } = await import('jspdf-autotable')

  const MONTHS  = ['January','February','March','April','May','June','July','August','September','October','November','December']
  const period  = `${MONTHS[month - 1]} ${year}`
  const doc     = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const w       = doc.internal.pageSize.getWidth()

  let y = makeHeader(doc, {
    churchName,
    title:  'Sunday School Monthly Attendance Report',
    period,
    adminName,
  })

  if (!sundays?.length) {
    doc.setFontSize(10)
    doc.setTextColor(...GRAY)
    doc.text('No records found for this month.', w / 2, y + 20, { align: 'center' })
    makeFooter(doc, { churchName, period })
    doc.save(`Attendance-${period.replace(' ', '-')}.pdf`)
    return
  }

  // ── One section per Sunday ─────────────────────────────────
  for (let i = 0; i < sundays.length; i++) {
    const s = sundays[i]

    // Section divider (not for first)
    if (i > 0) {
      doc.setDrawColor(...NAVY)
      doc.setLineWidth(0.3)
      doc.line(14, y, w - 14, y)
      y += 6
    }

    // Sunday heading
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...NAVY)
    doc.text(fmtDate(s.date), 14, y)
    y += 6

    // Sunday stats
    const rate = s.total > 0 ? Math.round((s.present / s.total) * 100) : 0
    autoTable(doc, {
      startY: y,
      head:   [['Present', 'Absent', 'Attendance Rate', 'Classes', 'Offering']],
      body:   [[
        s.present,
        s.absent || (s.total - s.present),
        `${rate}%`,
        s.classes,
        fmt(s.offering),
      ]],
      headStyles:   { fillColor: NAVY, textColor: WHITE, fontStyle: 'bold', fontSize: 8 },
      bodyStyles:   { fontSize: 9, fontStyle: 'bold' },
      margin:       { left: 14, right: 14 },
    })
    y = doc.lastAutoTable.finalY + 8

    // If page is getting full, add a new page
    if (y > 240 && i < sundays.length - 1) {
      doc.addPage()
      y = 20
    }
  }

  // ── Monthly summary at the end ─────────────────────────────
  doc.addPage()
  y = 20

  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...NAVY)
  doc.text('Monthly Summary', 14, y)
  y += 8

  const totalPresent  = sundays.reduce((s, d) => s + d.present,  0)
  const totalTotal    = sundays.reduce((s, d) => s + (d.total || (d.present + d.absent)), 0)
  const totalOffering = sundays.reduce((s, d) => s + (d.offering || 0), 0)
  const avgRate       = totalTotal > 0 ? Math.round((totalPresent / totalTotal) * 100) : 0

  autoTable(doc, {
    startY: y,
    head:   [['Metric', 'Value']],
    body: [
      ['Period',                     period],
      ['Total Sundays Recorded',      sundays.length],
      ['Total Members Present',       totalPresent.toLocaleString()],
      ['Total Members Absent',        (totalTotal - totalPresent).toLocaleString()],
      ['Average Attendance Rate',     `${avgRate}%`],
      ['Total Offering Collected',    fmt(totalOffering)],
      ['Highest Attendance Sunday',   fmtShort(sundays.slice().sort((a, b) => b.present - a.present)[0]?.date || '')],
      ['Lowest Attendance Sunday',    fmtShort(sundays.slice().sort((a, b) => a.present - b.present)[0]?.date || '')],
    ],
    headStyles:         { fillColor: NAVY, textColor: WHITE, fontStyle: 'bold', fontSize: 8 },
    bodyStyles:         { fontSize: 8 },
    alternateRowStyles: { fillColor: CREAM },
    columnStyles:       { 0: { fontStyle: 'bold', cellWidth: 70 } },
    margin:             { left: 14, right: 14 },
  })

  y = doc.lastAutoTable.finalY + 8

  // Per-Sunday breakdown table
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...NAVY)
  doc.text('Sunday Breakdown', 14, y)

  autoTable(doc, {
    startY: y + 4,
    head:   [['Date', 'Present', 'Absent', 'Rate', 'Classes', 'Offering']],
    body:   sundays.map(s => {
      const t    = s.total || (s.present + (s.absent || 0))
      const rate = t > 0 ? Math.round((s.present / t) * 100) : 0
      return [
        fmtShort(s.date),
        s.present,
        s.absent || (t - s.present),
        `${rate}%`,
        s.classes,
        fmt(s.offering),
      ]
    }),
    headStyles:         { fillColor: NAVY, textColor: WHITE, fontStyle: 'bold', fontSize: 8 },
    bodyStyles:         { fontSize: 8 },
    alternateRowStyles: { fillColor: CREAM },
    margin:             { left: 14, right: 14 },
  })

  if (groups?.length > 0) {
    y = doc.lastAutoTable.finalY + 8
    groupTable(doc, autoTable, y, groups)
  }

  makeFooter(doc, { churchName, period })
  doc.save(`Attendance-${period.replace(' ', '-')}.pdf`)
}