/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,jsx}',
    './src/components/**/*.{js,jsx}',
    './src/app/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          navy:        '#0F2557',
          'navy-light':'#1E3A6E',
          'navy-dark': '#0A1A3D',
          cream:       '#FAF6F0',
          'cream-dark':'#F0EAE0',
          'cream-border':'#E8DDD0',
        },
        ink: {
          DEFAULT: '#0F1729',
          muted:   '#4A5568',
          subtle:  '#718096',
        },
        status: {
          'success-bg':     '#ECFDF5',
          'success-border': '#6EE7B7',
          'success-text':   '#065F46',
          'success-icon':   '#059669',
          'pending-bg':     '#FFFBEB',
          'pending-border': '#FCD34D',
          'pending-text':   '#92400E',
          'pending-icon':   '#D97706',
          'error-bg':       '#FEF2F2',
          'error-border':   '#FCA5A5',
          'error-text':     '#991B1B',
          'error-icon':     '#DC2626',
          'approved-bg':    '#EFF6FF',
          'approved-border':'#93C5FD',
          'approved-text':  '#1E40AF',
        },
        gold: {
          DEFAULT: '#C9A84C',
          light:   '#FEF9EF',
          dark:    '#92650A',
        },
      },
      fontFamily: {
        heading: ['Plus Jakarta Sans', 'sans-serif'],
        body:    ['Inter', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['11px', { lineHeight: '1.4' }],
        xs:    ['12px', { lineHeight: '1.5' }],
        sm:    ['13px', { lineHeight: '1.5' }],
        base:  ['15px', { lineHeight: '1.6' }],
        md:    ['17px', { lineHeight: '1.5' }],
        lg:    ['20px', { lineHeight: '1.4' }],
        xl:    ['24px', { lineHeight: '1.3' }],
        '2xl': ['30px', { lineHeight: '1.2' }],
        '3xl': ['36px', { lineHeight: '1.1' }],
      },
      borderRadius: {
        sm:   '8px',
        md:   '12px',
        lg:   '16px',
        xl:   '20px',
        '2xl':'28px',
        '3xl':'36px',
      },
      boxShadow: {
        card:    '0 1px 4px rgba(15,37,87,0.06), 0 0 0 1px rgba(15,37,87,0.04)',
        'card-hover': '0 4px 16px rgba(15,37,87,0.10), 0 0 0 1px rgba(15,37,87,0.06)',
        modal:   '0 20px 60px rgba(15,37,87,0.18)',
        nav:     '0 -2px 12px rgba(15,37,87,0.06)',
        button:  '0 2px 8px rgba(15,37,87,0.25)',
        'button-lg': '0 4px 16px rgba(15,37,87,0.30)',
        inner:   'inset 0 1px 3px rgba(15,37,87,0.08)',
      },
      backgroundImage: {
        'navy-gradient': 'linear-gradient(135deg, #0F2557 0%, #1E3A6E 100%)',
        'navy-gradient-dark': 'linear-gradient(160deg, #0F2557 0%, #0A1A3D 100%)',
        'cream-gradient': 'linear-gradient(180deg, #FAF6F0 0%, #F0EAE0 100%)',
        'gold-gradient': 'linear-gradient(135deg, #C9A84C 0%, #A8862E 100%)',
      },
      spacing: {
        safe: 'env(safe-area-inset-bottom)',
      },
      animation: {
        'slide-up':    'slideUp 0.3s ease forwards',
        'fade-in':     'fadeIn 0.25s ease forwards',
        'scale-in':    'scaleIn 0.25s ease forwards',
        'pulse-dot':   'pulseDot 2s ease infinite',
        'skeleton':    'skeleton 1.4s ease-in-out infinite',
        'check-draw':  'checkDraw 0.4s ease forwards',
        'count-up':    'countUp 0.5s ease forwards',
      },
      keyframes: {
        slideUp:   { from:{ opacity:'0', transform:'translateY(14px)' }, to:{ opacity:'1', transform:'translateY(0)' } },
        fadeIn:    { from:{ opacity:'0' }, to:{ opacity:'1' } },
        scaleIn:   { from:{ opacity:'0', transform:'scale(0.95)' }, to:{ opacity:'1', transform:'scale(1)' } },
        pulseDot:  { '0%,100%':{ boxShadow:'0 0 0 0 rgba(5,150,105,0.4)' }, '50%':{ boxShadow:'0 0 0 8px rgba(5,150,105,0)' } },
        skeleton:  { '0%':{ backgroundPosition:'-400px 0' }, '100%':{ backgroundPosition:'calc(400px + 100%) 0' } },
        checkDraw: { from:{ strokeDashoffset:'100' }, to:{ strokeDashoffset:'0' } },
        countUp:   { from:{ opacity:'0', transform:'translateY(6px)' }, to:{ opacity:'1', transform:'translateY(0)' } },
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
}